# Generated by Django 4.1.3 on 2023-02-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='center1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('came_from', models.IntegerField()),
                ('to_go', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='center2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('came_from', models.IntegerField()),
                ('to_go', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='center3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('came_from', models.IntegerField()),
                ('to_go', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='center4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('came_from', models.IntegerField()),
                ('to_go', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='center5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('came_from', models.IntegerField()),
                ('to_go', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='center6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('came_from', models.IntegerField()),
                ('to_go', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='loginpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('adress1', models.CharField(max_length=50)),
                ('adress2', models.CharField(max_length=50)),
                ('start_b', models.IntegerField()),
                ('final_b', models.IntegerField()),
                ('path', models.CharField(max_length=50)),
                ('current_b', models.IntegerField(null=True)),
                ('current_center', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='useraccountregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=50)),
                ('Lasttname', models.CharField(max_length=50)),
                ('Username', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('other', 'other'), ('Female', 'Female')], default='Male', max_length=20)),
                ('State', models.CharField(choices=[('Punjab', 'Punjab'), ('West Benagal', 'West Bengal'), ('Delhi', 'Delhi')], default='Punjab', max_length=20)),
                ('city', models.CharField(choices=[('Patiala', 'Patiala'), ('kolkota', 'kolkota'), ('Delhi', 'Delhi')], default='patiala', max_length=20)),
                ('pincode', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='workeraccountregister',
            fields=[
                ('worker_id', models.AutoField(primary_key=True, serialize=False)),
                ('Firstname', models.CharField(max_length=50)),
                ('Lasttname', models.CharField(max_length=50)),
                ('Username', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('other', 'other'), ('Female', 'Female')], default='Male', max_length=20)),
                ('State', models.CharField(choices=[('Punjab', 'Punjab'), ('West Benagal', 'West Bengal'), ('Delhi', 'Delhi')], default='Punjab', max_length=20)),
                ('city', models.CharField(choices=[('Patiala', 'Patiala'), ('kolkota', 'kolkota'), ('Delhi', 'Delhi')], default='patiala', max_length=20)),
                ('pincode', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
