# Generated by Django 4.1.3 on 2023-02-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insideapp', '0006_alter_useraccountregister_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraccountregister',
            name='Gender',
            field=models.CharField(choices=[('Female', 'Female'), ('other', 'other'), ('Male', 'Male')], default='Male', max_length=20),
        ),
        migrations.AlterField(
            model_name='useraccountregister',
            name='city',
            field=models.CharField(choices=[('Delhi', 'Delhi'), ('Patiala', 'Patiala'), ('kolkota', 'kolkota')], default='patiala', max_length=20),
        ),
        migrations.AlterField(
            model_name='workeraccountregister',
            name='Gender',
            field=models.CharField(choices=[('Female', 'Female'), ('other', 'other'), ('Male', 'Male')], default='Male', max_length=20),
        ),
        migrations.AlterField(
            model_name='workeraccountregister',
            name='city',
            field=models.CharField(choices=[('Delhi', 'Delhi'), ('Patiala', 'Patiala'), ('kolkota', 'kolkota')], default='patiala', max_length=20),
        ),
    ]
