# Generated by Django 4.1.3 on 2023-02-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insideapp', '0009_alter_useraccountregister_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountregister',
            name='State',
            field=models.CharField(choices=[('Punjab', 'Punjab'), ('Delhi', 'Delhi'), ('West Benagal', 'West Bengal')], default='Punjab', max_length=20),
        ),
        migrations.AlterField(
            model_name='useraccountregister',
            name='city',
            field=models.CharField(choices=[('kolkota', 'kolkota'), ('Delhi', 'Delhi'), ('Patiala', 'Patiala')], default='patiala', max_length=20),
        ),
        migrations.AlterField(
            model_name='workeraccountregister',
            name='State',
            field=models.CharField(choices=[('Punjab', 'Punjab'), ('Delhi', 'Delhi'), ('West Benagal', 'West Bengal')], default='Punjab', max_length=20),
        ),
        migrations.AlterField(
            model_name='workeraccountregister',
            name='city',
            field=models.CharField(choices=[('kolkota', 'kolkota'), ('Delhi', 'Delhi'), ('Patiala', 'Patiala')], default='patiala', max_length=20),
        ),
    ]
