# Generated by Django 4.1.3 on 2023-02-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insideapp', '0015_remove_useraccountregister_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountregister',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('other', 'other'), ('Female', 'Female')], default='Male', max_length=20),
        ),
        migrations.AlterField(
            model_name='useraccountregister',
            name='city',
            field=models.CharField(choices=[('Patiala', 'Patiala'), ('kolkota', 'kolkota'), ('Delhi', 'Delhi')], default='patiala', max_length=20),
        ),
        migrations.AlterField(
            model_name='workeraccountregister',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('other', 'other'), ('Female', 'Female')], default='Male', max_length=20),
        ),
        migrations.AlterField(
            model_name='workeraccountregister',
            name='city',
            field=models.CharField(choices=[('Patiala', 'Patiala'), ('kolkota', 'kolkota'), ('Delhi', 'Delhi')], default='patiala', max_length=20),
        ),
    ]
